### PR TITLE
Fixed import modules

### PR DESCRIPTION
**Pull request by adw2011**
Got an error for the import statements in these two files, but what I'm really doing is testing the process of  creating pull requests.

### CODE REVIEW

**Comment by FFX01** [comment]
You shouldn't be getting an error for these imports. You are using Python3 correct?

**Comment by adw2011** [comment]
Yes, but might be something related to my virtualenv. Ill try and set it up again and see what happens.

**Comment by FFX01** [comment]
Did you get this to work? Can I close the issue?

**Comment by npaul2811** [comment]
Raise an issue first adw2011 and then create a corresponding PR for it. Good going though! Did you fix the errors?

**Comment by adw2011** [comment]
Will do, yes the error was on my part, ide related, so just delete the pull request.

**Pull request closed without merging**
